# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "AnanaSeek4Jam"
weight = 1

[ru]
languageName = "Russian"
languagedirection = "ltr"
title = "AnanaSeek4Jam"
weight = 1
