# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/AnanasikDev"

[social.params]
icon = "brand-github"

[[social]]
identifier = "bluesky"
name = "Bluesky"
url = "https://bsky.app/profile/ananaseek4jam.bsky.social"

[social.params]
icon = "brand-bluesky"

[[social]]
identifier = "youtube"
name = "Youtube"
url = "https://www.youtube.com/@ananaseek"

[social.params]
icon = "brand-youtube"

[[social]]
identifier = "itchdotio"
name = "Itch.io"
url = "https://ananasikdeveloper.itch.io/"

[social.params]
icon = "brand-itchdotio"

[[main]]
    name = "Portfolio"
    url = "/gallery"
    weight = 30
    [main.params]
        icon = "portfolio"
